// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9QlppXzl8pxgSRnHaWpk5UF6X3inRMz8',
    appId: '1:987596029908:web:c9da838f45206e2b992041',
    messagingSenderId: '987596029908',
    projectId: 'cowboy-trio-doonghwi',
    authDomain: 'cowboy-trio-doonghwi.firebaseapp.com',
    databaseURL: 'https://cowboy-trio-doonghwi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cowboy-trio-doonghwi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA00VrDOQctMf9gbN8-MUkKCBeB5RVqpbk',
    appId: '1:987596029908:android:1b35f9c955564cf3992041',
    messagingSenderId: '987596029908',
    projectId: 'cowboy-trio-doonghwi',
    databaseURL: 'https://cowboy-trio-doonghwi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cowboy-trio-doonghwi.firebasestorage.app',
  );
}
